### PR TITLE
Add images and edit templates for event branding

### LINKED ISSUE #4: Add hackathon logo & branding when available
Add the following elements:

- [x] Favicon of hackathon logo
- [x] Add logo to RHS of page header, next to docs title
header

### PR DESCRIPTION
**Pull request by etcadinfinitum**
Fixes #4 

After some goofing around with mobile views in Firefox, I discovered that this Jekyll template, and the docs pages in their current form, are not at all optimized for mobile. We should make that clear when informing folks about the docs pages.

Full size window, 768px display:
header
Half size window, same display:
header-half

### CODE REVIEW

**Review by RyanRussell00 — COMMENTED** [review]
Can we get the browser size and if it's less than the minimum size needed to be visible (say 1000px) then we can display a message saying "this site does not work on mobile platforms"?

**Comment by etcadinfinitum** [comment]
> Can we get the browser size and if it's less than the minimum size needed to be visible (say 1000px) then we can display a message saying "this site does not work on mobile platforms"?

Yes, that's probably something we can do. I will look into it over the weekend. I've never done media queries before but will fiddle with it :grin:

**Comment by RyanRussell00** [comment]
> > Can we get the browser size and if it's less than the minimum size needed to be visible (say 1000px) then we can display a message saying "this site does not work on mobile platforms"?
> 
> Yes, that's probably something we can do. I will look into it over the weekend. I've never done media queries before but will fiddle with it grin

I think it would be easier to implement with a single JS function that looks at screen size and redirects to another page that says "Not available on mobile"

**Review by cforcomputer — COMMENTED** [review]
You can also [specify alternative css styles for different screen resolutions](https://css-tricks.com/resolution-specific-stylesheets/). I think it would be cleaner to do that if we have time as opposed to disabling the site on mobile.

**Comment by etcadinfinitum** [comment]
@cforcomputer @RyanRussell00 I have added media queries which stacks sections vertically for a better mobile viewing experience, as well as adding a small div at the top of the page encouraging laptop usage instead of mobile browser. Screenshots of mobile view are here.

| Top of screen | Navigation Menu + Content |
| ---------------- | ------------------------------ |
| Screen Shot 2020-03-28 at 11 46 35 | Screen Shot 2020-03-28 at 11 47 23 |

**Review by cforcomputer — APPROVED** [review]
LGTM

**Pull request merged**
