### PR TITLE
AWS Product

### PR DESCRIPTION
**Pull request by redpandarevolt**
Add links and feature descriptions to all the most commonly used AWS Products.
(Need help with "You can do X with Y feature")

Added link and description to AWS educate and AWS Student Ambassador Program

Buttons were pushed, pull requests were created....excuse me while I pick my chin up off the ground.  **Mind Blown**

### CODE REVIEW

**Comment by redpandarevolt** [comment]
Huy looks good. Is there anything else that need to be added content wise?

**Review by huyn8 — APPROVED** [review]
LGTM

**Review by etcadinfinitum — APPROVED** [review]
The content looks good! I'm approving this, but I'd really like you to delete the `.DS_Store` file from your branch before you merge. There are lots of good instructions online [but I like this one best](https://code.likeagirl.io/how-to-get-rid-of-ds-store-and-node-modules-in-git-repositories-d37b8a391247).

**Comment by redpandarevolt** [comment]
.DS_Store is gone, gone, gone.

**Pull request merged**
